apiVersion: v1
kind: Pod
metadata:
  name: cert-pod
spec:
  restartPolicy: Never
  volumes:
    - name: cert-volume
      secret:
        secretName: ipsec-example
  containers:
    - name: test-container
      image: quay.io/ykashtan/nss-tools:latest
      imagePullPolicy: Always
      command:
        - sh
        - -c 
        - "while true; do sleep 30; done;"
      volumeMounts:
        - name: cert-volume
          readOnly: true
          mountPath: "/certs"
